imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: sk

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'NightSurveyBundle:Form:form.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
#                        auto_generate_proxy_classes: "%kernel.debug%"
                naming_strategy: doctrine.orm.naming_strategy.underscore
#                auto_mapping: true
                mappings:
                    NightSurveyBundle:
                        type: annotation
                    UserBundle:
                        type: annotation
                    FOSUserBundle:
                        type: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
                - "%kernel.root_dir%/../vendor/timhovius/bootstrap-material-design/less/ripples.less"
                - "%kernel.root_dir%/../vendor/timhovius/bootstrap-material-design/less/material.less"
                - "%kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less"
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
                - "%kernel.root_dir%/../vendor/timhovius/bootstrap-material-design/scripts/ripples.js"
                - "%kernel.root_dir%/../vendor/timhovius/bootstrap-material-design/scripts/material.js"
                - "%kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js"
            output: js/bootstrap.js
        theme_css:
            inputs:
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/css/theme.css"
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/css/circle.css"
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/css/jquery-ui.min.css"
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/css/jquery-ui.structure.min.css"
            output: css/theme.css
        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js"
            output: js/jquery.js
        application:
            inputs:
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/js/application.js"
                - "%kernel.root_dir%/../src/Night/SurveyBundle/Resources/js/jquery-ui.min.js"
            output: js/application.js


braincrafted_bootstrap:
    css_preprocessor: less
    fonts_dir: "%kernel.root_dir%/../web/fonts"
    assets_dir: "%kernel.root_dir%/../vendor/timhovius/bootstrap-material-design"
    auto_configure:
        twig: false
        assetic: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
          address:  'registrator@publeash.nightnr.com'
          sender_name:  'PubLeash - Registrator'
    registration:
          confirmation:
            enabled: true
          form:
            type: app_user_registration
    profile:
          form:
            type: fos_user_profile

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    connect:
            account_connector: app.user_provider
    fosub:
            username_iterations: 30
            properties:
                facebook:    facebook_id
                google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           241337559701820
            client_secret:       93964467c16fce85e49db35b577ff08d
            scope:               "email"
            options:
                display: popup
        google:
            type: google
            client_id: "256003520636-bftpaa593b5k2kbn051cccbdvo9l5pu9.apps.googleusercontent.com"
            client_secret: "AMgXcbNlSgnUBPV_UI52xpxi"
            scope: "email profile"

ornicar_gravatar: ~
